import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} 
      bg-[#f6f6f6]
         
      `}
      >
        <div className="min-h-screen flex flex-col items-center justify-center">
          <Header />
          <main className="flex-1 w-full h-full">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
